### ISSUE TITLE
Error generating routerdb

### ISSUE THREAD

**Issue by DanielSCBO** [itinero/idp#9]
Hello

I am trying to generate the routerdb from Portugal and I am having the following error

`Unhandled Exception: System.ArgumentException: Vertex 2147483648 does not exist.
   at Itinero.Graphs.Geometric.GeometricGraph.GetVertex(UInt32 vertex)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.TryGetValue(Int64 node, Coordinate& coordinate, Boolean& isCore)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.AddWay(Way way)
   at OsmSharp.Streams.OsmStreamTarget.DoPull(Boolean ignoreNodes, Boolean ignoreWays, Boolean ignoreRelations)
   at Itinero.IO.Osm.Streams.RouterDbStreamTarget.OnBeforePull()
   at OsmSharp.Streams.OsmStreamTarget.Pull()
   at IDP.Switches.RouterDb.SwitchCreateRouterDb.<>c__DisplayClass3_0.<Parse>b__0() in C:\TeamCity\BuildAgent\work\38ea682527d0dcc0\src\IDP\Switches\RouterDb\SwitchCreateRouterDb.cs:line 177
   at IDP.Switches.RouterDb.SwitchContractRouterDb.<>c__DisplayClass3_0.<Parse>b__0() in C:\TeamCity\BuildAgent\work\38ea682527d0dcc0\src\IDP\Switches\RouterDb\SwitchContractRouterDb.cs:line 95
   at IDP.Switches.RouterDb.SwitchWriteRouterDb.<>c__DisplayClass3_0.<Parse>b__0() in C:\TeamCity\BuildAgent\work\38ea682527d0dcc0\src\IDP\Switches\RouterDb\SwitchWriteRouterDb.cs:line 74
   at IDP.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\38ea682527d0dcc0\src\IDP\Program.cs:line 52`

I have already used the idp version 2.15.0 and the latest on win10-x64

My command line is : 

`idp --read-pbf F:\Maps\portugal-latest.osm.pbf --pr --create-routerdb vehicles=car --contract car --write-routerdb F:\Maps\PT.routerdb`

And download map from where http://download.geofabrik.de/europe/portugal-latest.osm.pbf

Any help?

Thanks

**Comment by DanielSCBO** [comment]
Resolved osm corrupt sorry
